# .github/workflows/lint.yml
name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Vérifie le code source
      - name: Set up Python 
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10'  # Définit la version de Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Met à jour pip
          pip install flake8 flake8-docstrings  # Installe flake8 et flake8-docstrings pour vérifier les docstrings
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics  # Vérifie les erreurs de code, y compris les erreurs liées aux docstrings
